---
name: Linting

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

permissions: {}

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: ".tool-versions"
      - name: Cache yarn dependencies
        id: yarn-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            .yarn/cache
            node_modules
          key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/.yarnrc.yml') }}"
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Run ESLint
        uses: sibiraj-s/action-eslint@bcf41bb9abce43cdbad51ab9b3da2eddaa17eab3 # v3
        with:
          all-files: "true"
          ignore-patterns: |
            .github
            .yarn
            coverage
            dist
            node_modules
          eslint-args: "-o eslint-results.sarif -f ${{ github.workspace }}/node_modules/@microsoft/eslint-formatter-sarif/sarif.js"
          extensions: "js,jsx,ts,tsx"
          annotations: true
      - name: Upload to GHAS
        if: always()
        uses: github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with:
          category: "eslint"
          sarif_file: "eslint-results.sarif"
  pre-commit:
    name: Pre-commit
    uses: fabasoad/reusable-workflows/.github/workflows/wf-pre-commit.yml@c5bd8945762dab6d2f5168b65f10355887ea40a3 # main
    with:
      skip-hooks: "audit, build, eslint, test, snyk-test"
