---
name: Sync labels

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch: {}

permissions: {}

jobs:
  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1
