---
name: License

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 5 1 1 *"

permissions: {}

jobs:
  maintenance:
    name: Maintenance
    uses: fabasoad/reusable-workflows/.github/workflows/wf-update-license.yml@5ebe0938b8d8ef97bbb051004c511ba78449a866 # main
